version: '3'

services:
  etl_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etl_finance_app
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=finance_data
      - DB_USER=etl_user
      - DB_PASSWORD=etl_password
    networks:
      - etl_network

  postgres:
    image: postgres:14
    container_name: etl_finance_db
    environment:
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
      POSTGRES_DB: finance_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema:/docker-entrypoint-initdb.d
      - ./sql/maintenance:/sql/maintenance
      #todo queries
    networks:
      - etl_network

  # Vos autres services existants...

networks:
  etl_network:
    driver: bridge

volumes:
  postgres_data: